# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dan Kir
phone: "+447514433198"
publickey: "https://raw.githubusercontent.com/dan-kir/pgp-public-key/main/dan-kir.asc"
shortid: "0x9EE81E9F"
description: > # this means to ignore newlines until "baseurl:"
  Whoami
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dan-kir.github.io" # the base hostname & protocol for your site
usernames:
  twitter: dankir__
  github:  dan-kir
  linkedin:
  stackexchange:
  delicious:
  pinboard:

# Build settings
markdown: kramdown
timezone: "+0100"

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: false
      mathjax:  false
      social:   true
